### ISSUE TITLE
Associated SharePoint groups not created when selecting unique permissions in subsite provisioning

### ISSUE THREAD

**Issue by amirkhanRC** [SharePoint/PnP-Partner-Pack#195]
Using the PnP Partner Pack ( latest build)  we noticed that while creating sub-sites we choose the below option to break inheritance from the site collection

![break-inheritance](https://cloud.githubusercontent.com/assets/20151481/21314014/19dde32c-c5f5-11e6-8ebb-7f185581cb05.PNG)

However when checking the site permissions of the newly created sub-site, we see that no associated SharePoint groups (Owner, Member, Visitor) were created. 

![nogroups](https://cloud.githubusercontent.com/assets/20151481/21314171/c65d1c58-c5f5-11e6-9a90-eabd90cbab00.PNG)

Is the creation of these groups not being picked up in the sub-site provisioning handler? If so, is there a plan to add this?

Amir
PS. It would also be useful to be able to add additional owners, members, visitors from the sub-site creation view.

**Comment by biste5** [comment]
Hi Amir,

I can verify the issue you report.
Since August 2015, there's finally in CSOM a method for creating default associated groups in one shot (API call)
[New SharePoint CSOM version released for SharePoint Online - August 2016 Updated](https://dev.office.com/blogs/new-sharepoint-csom-version-released-for-Office-365-august-2016-updated)

_public **method** Microsoft.SharePoint.Client.**Web.CreateDefaultAssociatedGroups**_  
is then available since CSOM version 16.1.5626.1200

This should be implemented then in _SubSiteProvisioningJobHandler_
I can implement this as the default for when _InheritPermissions_ is _false_ for us, but for the implementation change to commit on this official repo we need to align with @PaoloPia and other contributors on what is the default implementation to choose for the provisioning job.

For instance: 
- always create default associated groups when sub site doesn't inherit permissions?
- who to set as initial owners of the associated groups?

Massimo

**Comment by biste5** [comment]
@PaoloPia , the fix is easier than thought in terms of requirements, and can be simply implemented by adding in [SubSiteProvisioningJobHandler](https://github.com/SharePoint/PnP-Partner-Pack/blob/dev/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.Infrastructure/Jobs/Handlers/SubSiteProvisioningJobHandler.cs)

```c#
if (job.InheritPermissions == false)
{
    web.CreateDefaultAssociatedGroups(string.Empty, string.Empty, string.Empty);
    context.ExecuteQueryRetry();
}
```

However, I still have two questions:

1. Is this implementation wished? In theory every site should have proper associated groups, and without this implementation they may be missing in provisioned sites

2. This introduces dependency on a method that is only available in CSOM for SPO.
Should then different build configurations, and reference local assemblies instead of NuGet packages, be applied to Partner Pack solution, as it's done for the core library?

**Comment by PaoloPia** [comment]
Hi Massimo,
The fix is ok and about your questions:
1) It's ok, just merged into #200
2) No worries about an SPO dependency. So far, we just support SPO.

Thanks,
Paolo

**Comment by sharepointryan** [comment]
Does the web.CreateDefaultAssociatedGroups() method support adding a default user? I've tried many ways to have it add the job.Owner as the default owner of each of the groups without success. I've also tried adding code to the SubSiteProvisioningJobHandler to manually add a user to the group(s), without success. Can you advise as to how we can ensure the requesting user gets added to the new webs?

**Comment by biste5** [comment]
So this is a question more for the SP team to document this CSOM method properly
[Web.CreateDefaultAssociatedGroups method](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.web.createdefaultassociatedgroups.aspx)

Anyway, from my recent experience that should be supported by _userLogin_ and _userLogin2_ method parameters, which expect a user's login name without the claims prefix (e.g. admin@contoso.com).
That user will be added as additional member to the created Owners group.

If you want to implement it in a safer and more extensible way (so that is not limited to just one or two extra users), you can extend the classes of PnP Partner Pack, for instance `SubSiteProvisioningJob` model class, so that it will carry extra properties containing additional users to add to groups.

```c#
public class SubSiteProvisioningJob : SiteProvisioningJob
{
	...

	public String[] AdditionalSiteOwners { get; set; }
	public String[] AdditionalSiteMembers { get; set; }
}
```

**SubSiteProvisioningJobHandler::CreateSubSite**

```c#
...
if (job.InheritPermissions == false)
{
	web.CreateDefaultAssociatedGroups(string.Empty, string.Empty, string.Empty);
	parentContext.ExecuteQueryRetry();

	if (job.AdditionalSiteOwners.Any())
	{
		var group = web.AssociatedOwnerGroup;
		foreach (var ao in job.AdditionalSiteOwners)
		{
			var user = web.EnsureUser(ao);
			group.Users.AddUser(user);
		}
		group.Update();
	}

	if (job.AdditionalSiteMembers.Any())
	{
		var group = web.AssociatedMemberGroup;
		foreach (var am in job.AdditionalSiteMembers)
		{
			var user = web.EnsureUser(am);
			group.Users.AddUser(user);
		}
		group.Update();
	}

	if (job.AdditionalSiteOwners.Any() || job.AdditionalSiteMembers.Any())
	{
		parentContext.ExecuteQueryRetry();
	}
}
...
```

Hope this helps
