### ISSUE TITLE
Navigation - not able to parse a particular term set id like below to Guid 

### ISSUE THREAD

**Issue by nikhilsarvaiye** [SharePoint/PnP-Partner-Pack#208]
I am trying to apply a template to a different tenant site(which should not create much difference except the Site Security and Users which I have excluded)

I have below term set id: 
``{termsetid:Site Collection - {{tenant}}.sharepoint.com-sites-{{SiteName}}:Site Navigation}``
and issue at below line with below provided term set id where it try to parse it to first parser.parse and then Guid,

``navigationSettings.GlobalNavigation.TermSetId = Guid.Parse(parser.ParseString(template.Navigation.GlobalNavigation.ManagedNavigation.TermSetId));
                                break;
``

The issue is at above highlighted line

I am debugging it with PnP-Core code base

This issue is both with Global and Side-Nav.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. The issue you are highlighting should have been fixed in the Feb 2017 master release of the PnP Provisioning Engine, which is used by the PnP Partner Pack. Could you plese retry, after having updated your environment with the latest bits, and let us know? Thanks.

**Comment by PaoloPia** [comment]
Hi,
I dig into the issue and I can confirm that if you don't create the TermSet before provisioning a site, the provisioning job will fail. In the April 2017 release we made it possible to skip this issue, but we cannot provision the TermSet during the provisioning of the site, because we're provisioning using an App-Only token, which cannot be used to write the Term Store.
I will close this item, because we cannot do anything more than what we did, unfortunately.
