### ISSUE TITLE
I do not see the feature Save site as provisioning template

### ISSUE THREAD

**Issue by sogrjp** [SharePoint/PnP-Partner-Pack#212]
I have installed the PNP Partner Pack solution but now I have the following problems:
- I can not see the feature Save site as provisioning template. I do not know what I have to do to activate it.
- When I try to create a site collection,the only template that works for me is the Empty Site Template. But If I enable the Apply Tenant Branding option, site creation does not work. I get the following error "Composed look 'SharePointBranding' can not be found; pass null or empty to set look directly (not based on an existing entry)"
- I do not see the Create Sub Site option. How can I create a subsite?

**Comment by biste5** [comment]
1. > I can not see the feature Save site as provisioning template. I do not know what I have to do to activate it.

Navigate to the URL where you published PnP Partner Pack in Azure, log in as admin, and navigate to 'Settings' in PnP Partner Pack. You have a dropdown there where you have to select your site collection, and press 'Enable PnP Partner Pack' button

2. > When I try to create a site collection,the only template that works for me is the Empty Site Template. But If I enable the Apply Tenant Branding option, site creation does not work. I get the following error "Composed look 'SharePointBranding' can not be found; pass null or empty to set look directly (not based on an existing entry)"

There can be many reasons for this. It could be a bug. Please open a separate issue describing as best as possible your template, and the detailed error you get

3. > I do not see the Create Sub Site option. How can I create a subsite?

If you apply what at answer 1. on your site collection, then when doing 'New subsite' from 'Site Contents' page of your site, you'll be redirected to PnP Partner Pack instead of default SharePoint UI for creating a sub site

**Comment by sogrjp** [comment]
The problem was the parameter AzureWebSiteUrl from file  OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.SiteProvisioning\Templates\Overrides\PnP-Partner-Pack-Overrides.xml . I have modified this url becasuse it must be ssl (https)

Now I can see the capabilities Pnp in Site Collection, I can see feature Save site as provisioning template and  but  the job is Pending all the time. Any idea what is happen?
Where can I look that is what is failing?

**Comment by biste5** [comment]
I see, correct what you say about the Url that must be https.

For having the template being extracted (saved), you need to **deploy `ScheduledJob` project as a Web Job** in the same App Service, **and create a schedule for it in a Job Scheduler Collection, or run it manually**.

This, as well as accessing the logs can be done via the Azure Portal.
Navigate to the App Service where Partner Pack is deployed, then Settings and Web Jobs

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I suggest you to use the new setup wizard that we released a couple of days ago. You can find it in the DEV branch, still in preview. The tool will provide the right settings for all the services and jobs, and it will also provision the webjobs for you. I will close this item, but in case of any further need, let me know and I will be more than happy to re-open the issue. Thanks.

**Comment by jkovach82** [comment]
sogrjp did you ever get your issue with getting the PnP features working on your site?

**Comment by amitsaraswat83** [comment]
job always fails with the following error:

Composed look 'SharePointBranding' can not be found; pass null or empty to set look directly (not based on an existing entry)

Any assistance would be greatly appreciated.
