### ISSUE TITLE
Duplicate Azure app when deploying using the setup tool.

### ISSUE THREAD

**Issue by karenwhy** [SharePoint/PnP-Partner-Pack#246]
Published the PnP partner pack using the new Setup tool to a 30-day trial subscription in Azure in the same instance as our O365 tenant.
There are two instances of the 'PnP Partner Pack Setup Wizard' app in Azure with two different publishers.
![azureapps](https://cloud.githubusercontent.com/assets/26544921/24103636/e2628be6-0d4d-11e7-8fa0-0204832dd14b.png)

There are also two app tiles for the 'PnP Partner Pack Setup Wizard' in Office 365 under New Apps.
Neither of them work. When they are 'clicked' the following error message is displayed:

something went wrong...
You cannot access this application because it has been misconfigured. Contact your IT department and include the following information: Undefined Sign-On URL for application "PnP Partner Pack Setup Wizard".
![pnperror](https://cloud.githubusercontent.com/assets/26544921/24103454/4e9d2a1a-0d4d-11e7-8a25-6db410f351ca.png)

**Comment by PaoloPia** [comment]
Hi,
You see two apps registered because (as far as I can argue) you used the Azure subscription that sits under the cover of your Office 365 tenant to host both the PnP Partner Pack application registration in Azure AD and the services (Azure App Service, Azure Blob Storage, etc.) used to run the PnP Partner Pack on Azure. I mean: within the Wizard you provided the same set of credentials twice. Is it right?

I usually suggest to use a dedicate Azure subscription to host the infrastructural services, but it is totally ok to use the same subscription of Office 365. Nevertheless, in such scenario you will find two different applications with name "PnP Partner Pack Setup Wizard" registered within the same Azure AD Tenant. It is correct, because they are effectively two different applications with two different client IDs, just sharing the same name.

About the error that occurs when you start those applications from the App Laucher, I'm sorry to say that it is right, too. In fact, those applications are not intended to be used from the Web UI, and they are native applications.
The only application, related to the PnP Partner Pack, that you should start from the App Launcher of Office 365 is the "PnP Partner Pack" one.

I will close this issue, but it is good to keep track of your request and of this response for anybody else, who could have the same question. 
Thanks.
