### ISSUE TITLE
'ScheduledJob' Web job kick off issue

### ISSUE THREAD

**Issue by ravi-bamrotiya** [SharePoint/PnP-Partner-Pack#268]
Hello,

I used setup wizard to configure PnP-Partner Pack.
I can request for new site collection successfully but it stays in 'Pending' stage until and unless I start 'ScheduledJob' web-job manually.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We intentionally do not schedule the Scheduled Job for you, because you would incur in extra charges in your Azure subscription. You can start it manually, or you can follow these instructions: https://github.com/SharePoint/PnP-Partner-Pack/blob/master/Documentation/Manual-Setup-Guide.md#publishing-the-scheduledjob-using-a-minute-schedule-azure-scheduler
