### ISSUE TITLE
Using a composed look results in File Not Found

### ISSUE THREAD

**Issue by sharepointryan** [SharePoint/PnP-Partner-Pack#288]
Hello PNP team and contributors, no matter how I try to utilize a composed look/theme - my sites are always created with a 'File not found' error on the home page. It doesn't appear to matter if I create a template from XML, or if I export from an existing branded site using either PowerShell or the 'save as provisioning template' option in Site Settings. 

What is the correct approach for creating sites with a composed look applied? Are there any good samples of how the XML should be constructed and where the theme files should be stored?

Thanks!

**Comment by awildash** [comment]
Guessing you've probably solved this by now but thought I'd post my solution to this in case it saves others time. My issue was that when running as a scheduled job in Azure I couldnt figure out which relative path to use in my PnP Template to get it to go back \home\site\wwwroot\themes where I'd uploaded my custom spcolor file. It would appear the job runs in a temp folder with a directory structure like:

D:\local\Temp\jobs\triggered\ScheduledJob\ez2hrkk4.zuh

So you'd think in your PnP template you could upload your .spcolor file with something like:

`  <pnp:Files>
	<pnp:File Src="..\..\..\..\..\..\home\site\wwwroot\Themes\custom-theme.spcolor" Folder="{themecatalog}/15" Overwrite="true" />
 </pnp:Files> `

But nope, always file not found and I tried many variants and checked the at runtime File.Exists for my spcolor file was indeed true. But then I stumbled upon a message about [FileSystemConnector](https://github.com/SharePoint/PnP-Sites-Core/issues/496). So I modified the template SiteCollectionProvisioningJobHandler.cs to set the Connector property just before ApplyProvisioningTemplate is called using the HOME environment variable. So:

` string environmentPath = Path.Combine(Environment.GetEnvironmentVariable("HOME"), "site\\wwwroot");
                            template.Connector = new OfficeDevPnP.Core.Framework.Provisioning.Connectors.FileSystemConnector(environmentPath, "");`

Now if I've uploaded my custom Themes into a \Themes in the PnP web project I can change my template to be:

`  <pnp:Files>
	<pnp:File Src="Themes\custom-theme.spcolor" Folder="{themecatalog}/15" Overwrite="true" />
 </pnp:Files> 
 <pnp:ComposedLook Name="Current" ColorFile="{themecatalog}/15/custom-theme.spcolor" FontFile="" BackgroundFile="" Version="0" />    `

Because I know Connector will be working from wwwroot now. No idea where it thought it was operating before. And it all gets applied now.

Happy to be corrected on a better way to do it, but thought I'd post this in case its helpful.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
