### ISSUE TITLE
Moving to Microsoft Flow with Azure Function for provisioning

### ISSUE THREAD

**Issue by leedale1981** [SharePoint/PnP-Partner-Pack#301]
With the upcoming Site Designs flow of provisioning modern sites, I got wondering whether it would be worth moving the Partner Pack site creation process to doing something similar.

Currently the Partner Pack uses WebJobs to handle the actual site creation process. Could this be moved to using a Flow that is triggered from an Azure Queue entry? The flow then calls out to an Azure Function to use CSOM or Poweshell to create a site including modern team sites. This could also support things like creating Office 365 Groups. The templating would still use PnP.

The benefit I see here is not having to host WebJobs and possibly lowering cost by using Azure Functions.

**Comment by AndrewJolly** [comment]
I'm with you on your suggestion, I think there's also some other benefits - I could be off here but I'm pretty sure I read that because the partner pack is an Azure AD Application it doesn't support setting managed metadata values within SharePoint. I think the Azure Queue, Azure Function could be architected to be really extensible with the community generating and contributing to lots of PowerShell code that can be slotted in, this means you could start very very small with one site template provisioning and then go wider and scale out as your organisation matures.

**Comment by jwiersem** [comment]
Or use Automation?
http://www.avtex.com/2018/06/azure-automation-provisioning/

**Comment by PaoloPia** [comment]
Hi,
Thanks for your submission. We're sorry to inform you that we archived this repository and the PnP Partner Pack project will not be anymore supported. If you need to use something like that, we suggest you to move to the modern UI of SharePoint and to have a look at the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/).

If you still need to use and/or improve the PnP Partner Pack, you can download your own copy from this repository and work on that one.

Thanks for your support.
